name: APIgen CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: APIGen CI Steps
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm i
